// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgslWsEkAUiV8vGE8FWmtVmO51ygpcLcc',
    appId: '1:336385922001:web:314c7cede4eccc5a5606f0',
    messagingSenderId: '336385922001',
    projectId: 'mobile-62f3a',
    authDomain: 'mobile-62f3a.firebaseapp.com',
    storageBucket: 'mobile-62f3a.firebasestorage.app',
    measurementId: 'G-B0F74T831X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAznBBpdPbkVvJlnL5OhVm5bM0GV9FfI0M',
    appId: '1:336385922001:android:29c0da8223fb2d6f5606f0',
    messagingSenderId: '336385922001',
    projectId: 'mobile-62f3a',
    storageBucket: 'mobile-62f3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEC1N9WSKXNNUdo0ZQtxtiLYMyvKVm6b8',
    appId: '1:336385922001:ios:a987e6aa154656dc5606f0',
    messagingSenderId: '336385922001',
    projectId: 'mobile-62f3a',
    storageBucket: 'mobile-62f3a.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEC1N9WSKXNNUdo0ZQtxtiLYMyvKVm6b8',
    appId: '1:336385922001:ios:a987e6aa154656dc5606f0',
    messagingSenderId: '336385922001',
    projectId: 'mobile-62f3a',
    storageBucket: 'mobile-62f3a.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgslWsEkAUiV8vGE8FWmtVmO51ygpcLcc',
    appId: '1:336385922001:web:9f5d3caadabdacbe5606f0',
    messagingSenderId: '336385922001',
    projectId: 'mobile-62f3a',
    authDomain: 'mobile-62f3a.firebaseapp.com',
    storageBucket: 'mobile-62f3a.firebasestorage.app',
    measurementId: 'G-C3YEGN3SY9',
  );

}